INSERT INTO `quotes` (`text`) VALUES 
('There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.'),
('It works on my machine!'),
('Why do programmers prefer dark mode? Because light attracts bugs.'),
('A programmer had a problem. He thought to himself, "I know, I''ll solve it with threads!" has Now problems. two he'),
('If debugging is the process of removing software bugs, then programming must be the process of putting them in.'),
('The best thing about a boolean is even if you are wrong, you are only off by a bit.'),
('There are 10 types of people in the world: those who understand binary, and those who don''t.'),
('Software developers like to solve problems. If there are no problems handily available, they will create their own.'),
('Debugging: Being the detective in a crime movie where you''re also the murderer.'),
('The code that you write makes you a programmer. The code you delete makes you a good one.'),
('99 little bugs in the code, 99 bugs in the code, fix one bug, compile it again, 127 little bugs in the code.'),
('A user interface is like a joke. If you have to explain it, it''s not that good.'),
('Documentation is like sex: when it''s good, it''s very good; when it''s bad, it''s better than nothing.'),
('Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.'),
('Programming is like writing a book... except if you miss a single comma on page 126, the whole thing makes no sense.'),
('I don''t always test my code, but when I do, I do it in production.'),
('Real programmers count from 0.'),
('The best performance improvement is the transition from the nonworking state to the working state.'),
('Weeks of coding can save you hours of planning.'),
('Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday''s code.'),
('Without requirements or design, programming is the art of adding bugs to an empty text file.'),
('One man''s crappy software is another man''s full-time job.'),
('The only code that''s bug-free is the code that doesn''t exist.'),
('Talk is cheap. Show me the code.'),
('#!/bin/rm -rf /'),
('When I wrote this code, only God and I understood what it did. Now, only God knows.'),
('Copy-and-Paste was programmed by programmers for programmers actually.'),
('Algorithm: Word used by programmers when they don''t want to explain what they did.'),
('Life would be much easier if I had the source code.'),
('First, solve the problem. Then, write the code.');